version: "3.7"

services:
  db:
    restart: always
    image: postgres:12.11-alpine
    container_name: mailing_db
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - TZ=Asia/Yekaterinburg
  app:
    restart: always
    container_name: mailing_app
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ${PWD}/mailing_service/logging/logger.log:/usr/src/app/mailing_service/logging/logger.log
    build: .
    command: bash -c "python manage.py migrate & python manage.py collectstatic --noinput & gunicorn -w 3 --chdir . config.wsgi —bind 0.0.0.0:8000"
    env_file: ./.env
    ports:
      - ${PORT}:8000
    environment:
      - TZ=Asia/Yekaterinburg
    depends_on:
      - db
  redis:
    restart: always
    container_name: mailing_redis
    image: redis:alpine
    environment:
      - TZ=Asia/Yekaterinburg
  celery_worker:
    restart: always
    container_name: mailing_celery_worker
    build:
      context: .
    command: celery -A config worker -l info
    volumes:
      - ${PWD}/mailing_service/logging/logger.log:/usr/src/app/mailing_service/logging/logger.log
    env_file: ./.env
    environment:
      - TZ=Asia/Yekaterinburg
    depends_on:
      - db
      - redis
      - app
  celery_beat:
    restart: always
    container_name: mailing_celery_beat
    build:
      context: .
    command: celery -A config beat -l info
    volumes:
      - ${PWD}/mailing_service/logging/logger.log:/usr/src/app/mailing_service/logging/logger.log
    env_file: ./.env
    environment:
      - TZ=Asia/Yekaterinburg
    depends_on:
      - db
      - redis
      - app
  nginx:
    restart: always
    build: ./nginx/
    container_name: mailing_nginx
    volumes:
      - ${PWD}/mailing_service/logging/logger.log:/usr/src/app/mailing_service/logging/logger.log
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  db_volume:
  static_volume:
  media_volume:
