# Generated by Django 4.1 on 2022-08-23 20:56

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_client_mobile_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET'),
        ),
    ]
