# Generated by Django 4.1 on 2022-08-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_client_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='application.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='notification_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='application.notification'),
        ),
    ]
