# Generated by Django 4.1 on 2022-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_message_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sending_filter',
            field=models.JSONField(default={'mobile_code_operator': None, 'tag': None}),
        ),
    ]
