# Generated by Django 4.1 on 2022-08-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_message_sending_datetime_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['id'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sending_filter',
            new_name='mailing_filter',
        ),
    ]
