# Generated by Django 4.1 on 2022-08-27 21:19

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_client_mobile_operator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reached_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Mobile operator code must have a length of 3', regex='^\\d{3}$')]),
        ),
    ]
