# Generated by Django 4.1 on 2022-08-28 01:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_notification_reached_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reached_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), blank=True, default=list, size=None),
        ),
    ]
