# Generated by Django 4.1 on 2022-08-23 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0003_alter_client_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 7XXXXXXXXXX', regex='^\\+?7\\d{10}$')]),
        ),
    ]
