# Generated by Django 4.1 on 2022-08-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0007_notification_text_alter_message_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing_service.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='notification_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing_service.notification'),
        ),
    ]
