# Generated by Django 4.1 on 2022-08-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0009_notification_sending_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_send',
            new_name='is_sending',
        ),
    ]
