# Generated by Django 4.1 on 2022-08-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0010_rename_is_send_message_is_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sending_filter',
            field=models.JSONField(),
        ),
    ]
