# Generated by Django 4.1 on 2022-08-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0011_alter_notification_sending_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='notification_id',
            new_name='notification',
        ),
    ]
