# Generated by Django 4.1 on 2022-08-26 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0014_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='The mobile operator code must have a length of 3', regex='^\\d{3}$')]),
        ),
    ]
