# Generated by Django 4.1 on 2022-09-05 12:46

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0017_alter_notification_reached_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_operator_code',
            field=models.CharField(db_index=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Mobile operator code must have a length of 3', regex='^\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reached_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), blank=True, db_index=True, default=list, size=None),
        ),
    ]
