# Generated by Django 4.1 on 2022-11-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0018_alter_client_mobile_operator_code_alter_client_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_clients', to='mailing_service.client')),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_clients', to='mailing_service.notification')),
            ],
            options={
                'verbose_name': 'success_client',
                'verbose_name_plural': 'success_clients',
                'ordering': ['id'],
            },
        ),
    ]
