# Generated by Django 4.1 on 2022-11-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0019_successclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reached_numbers',
        ),
    ]
