# Generated by Django 4.1 on 2022-11-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0020_remove_notification_reached_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
