# Generated by Django 4.1 on 2022-11-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0021_alter_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successclient',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='successclient',
            old_name='notification_id',
            new_name='notification',
        ),
    ]
